export const SET_SCROLLSPY_DATA = 'SCROLLSPY/SET_SCROLLSPY_DATA';
export const TOGGLE_SCROLLSPY_VISIBILITY = 'SCROLLSPY/TOGGLE_SCROLLSPY_VISIBILITY';
export const CLOSE_SCROLLSPY_VISIBILITY = 'SCROLLSPY/CLOSE_SCROLLSPY_VISIBILITY';
