
export const FETCH_ARTICLE_BEGIN = 'ARTICLE/FETCH_ARTICLE_BEGIN';
export const FETCH_ARTICLE_SUCCESS = 'ARTICLE/FETCH_ARTICLE_SUCCESS';
export const FETCH_ARTICLE_FAILURE = 'ARTICLE/FETCH_ARTICLE_FAILURE';

export const FETCH_ARTICLE_LIST_BEGIN = 'ARTICLE/FETCH_ARTICLE_LIST_BEGIN';
export const FETCH_ARTICLE_LIST_SUCCESS = 'ARTICLE/FETCH_ARTICLE_LIST_SUCCESS';
export const FETCH_ARTICLE_LIST_FAILURE = 'ARTICLE/FETCH_ARTICLE_LIST_FAILURE';
