export const FETCH_BANNER_IMAGE_SUCCESS = 'HOME/FETCH_BANNER_IMAGE_SUCCESS';
export const FETCH_ABOUT_US_BEGIN = 'HOME/FETCH_ABOUT_US_BEGIN';
export const FETCH_ABOUT_US_COMPLETE = 'HOME/FETCH_ABOUT_US_COMPLETE';
